server:
  port: 8082
#  servlet:
#    context-path: /consumer-service
spring:
  application:
    name: consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

