server:
  port: 9000
spring:
  application:
    name: elk-es
  data:
    elasticsearch:
      # \u6307\u5B9Aelasticsearch\u96C6\u7FA4\u5730\u5740
      cluster-name: elasticsearch-cluster
      cluster-nodes: 192.168.25.21:9200
  kafka:
    bootstrap-servers: 192.168.25.21:9092
    consumer:
      group-id: kafka_elk_group
      enable-auto-commit: true
      auto-commit-interval: 3000
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    jedis:
      pool:
        maxActive: 300
        maxIdle: 100
        maxWait: 1000
    sysName: admin
    enable: true
    database: 0
  elasticsearch:
    rest:
      uris: 192.168.25.21:9200

kafka:
  topic: kafka_elk_log
