server:
  port: 8081
#Seata分布式事务配置(AT模式)
seata:
  enabled: true
  application-id: nacos-service-provider
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: ""
      password: ""
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: "SEATA_GROUP"
      username: ""
      password: ""