server:
  port: 8081
#  servlet:
#    context-path: /provider-service
spring:
  application:
    name: provider-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

