server:
  port: 6001

spring:
  application:
    name: order-service
  profiles:
    include: common
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
kafka:
  topic: PAY_SERVICE_DEDUCE
  partNum: 3
  repeatNum: 1
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true