server:
  port: 8080
spring:
  application:
    name: shatding-springboot-mybatis
mybatis:
  type-aliases-package: com.rule.entity
  mapper-locations: com/rule/mapper/*.xml
sharding:
  jdbc:
    datasource:
      names: master,slave1
      # \u6570\u636E\u6E90 master
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/master?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 123456
      # \u6570\u636E\u6E90 slave1
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/slave1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 123456
    config:
      sharding:
        props:
          sql.show: true
        tables:
          t_user: #t_user\u8868
            key-generator-column-name: id  #\u4E3B\u952E
            actual-data-nodes: master.t_user,slave1.t_user    #\u6570\u636E\u8282\u70B9,\u5747\u5300\u5206\u5E03
        defaultDatabaseStrategy:
          standard:
            sharding-column: id
            precise-algorithm-class-name: com.rule.algorithm.ShardingAlgorithm