spring:
  application:
    name: elk-es
  elasticsearch:
    rest:
      uris: 192.168.25.21:9200
  kafka:
    bootstrap-servers: 192.168.25.21:9092
    consumer:
      group-id: binlog_sync
      enable-auto-commit: true
      auto-commit-interval: 3000
# binlog\u914D\u7F6E
binlog:
  database:
    # \u6307\u5B9A\u76D1\u542C\u7684\u8868\u683C
    table: test.t_user,test.t_user_1
  host: 127.0.0.1
  user: root
  password: 123456
  port: 3306
server:
  id: 1
# kafka
kafka:
  partNum: 3
  repeatNum: 1
  topic: binlog
