management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081

spring:
  application:
    name: cloud-snetinel
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080